# DataSource Config
Spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/case_blog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
shiro-redis:
  enabled: true
  redis-mamanger:
    host: 127.0.0.1:6379
vblog:
  jwt:
    # 加密密钥
    secret: f4e2e52034348f86b67cde581c0f9eb5
    # token有效时长 7天 单位秒
    expire: 604800
    header: x-user-token